// <auto-generated />
using System;
using KungConnect.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KungConnect.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307180000_AddMachineSystemInfo")]
    partial class AddMachineSystemInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // (model snapshot omitted — see AppDbContextModelSnapshot.cs)
#pragma warning restore 612, 618
        }
    }
}
