<#
.SYNOPSIS
    Harvests all files from a .NET publish directory into a WiX v4 AgentFiles.wxs.

.DESCRIPTION
    Replaces "wix heat dir" (WiX v3) for WiX v4 builds that do not have the
    Harvest extension.  Generates one Component per file under $(AgentBinDir),
    preserving subdirectory structure.  The component that owns
    KungConnect.Agent.exe is named AgentExeComp and carries KeyPath="yes",
    ServiceInstall, and ServiceControl so that Windows Installer properly runs
    the InstallServices action.

.PARAMETER SourceDir
    Root of the dotnet-published output directory (e.g. dist\agent-win-x64).

.PARAMETER OutputFile
    Path to write the generated WXS (e.g. installer\windows\AgentFiles.wxs).

.PARAMETER ServiceName
    Windows service name. Default: KungConnectAgent

.EXAMPLE
    .\harvest-agent.ps1 -SourceDir dist\agent-win-x64 `
                        -OutputFile installer\windows\AgentFiles.wxs
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string] $SourceDir,
    [Parameter(Mandatory)][string] $OutputFile,
    [string] $ServiceName    = "KungConnectAgent",
    [string] $ServiceDisplay = "KungConnect Agent",
    [string] $ServiceDesc    = "KungConnect remote-management agent"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$SourceDir = (Resolve-Path $SourceDir).Path.TrimEnd('\')

# ── helpers ──────────────────────────────────────────────────────────────────

function To-WixId([string]$s) {
    # WiX identifiers: [A-Za-z_][A-Za-z0-9_.]*  max 72 chars
    $id = $s -replace '[^A-Za-z0-9_.]', '_'
    if ($id -match '^\d') { $id = '_' + $id }
    if ($id.Length -gt 72) { $id = $id.Substring(0, 72) }
    return $id
}

function New-DeterministicGuid([string]$seed) {
    # SHA-1 based name-UUID (RFC 4122 §4.3, variant/version bits set)
    $sha1  = [System.Security.Cryptography.SHA1]::Create()
    $bytes = [byte[]]($sha1.ComputeHash([System.Text.Encoding]::UTF8.GetBytes("KungConnectAgent:$seed")))
    $sha1.Dispose()
    # Force version=5, variant=10xx
    $bytes[6] = ($bytes[6] -band 0x0F) -bor 0x50
    $bytes[8] = ($bytes[8] -band 0x3F) -bor 0x80
    # [Guid]::new(byte[]) uses MS-GUID byte order (Data1/2/3 little-endian)
    # Build a proper 16-byte array
    $g = [byte[]](New-Object byte[] 16)
    [Array]::Copy($bytes, $g, 16)
    return ([guid]::new($g)).ToString('B').ToUpper()
}

# ── collect files ─────────────────────────────────────────────────────────────

$files = Get-ChildItem -LiteralPath $SourceDir -Recurse -File | Sort-Object FullName

if ($files.Count -eq 0) {
    throw "No files found in '$SourceDir'"
}

Write-Host "Harvesting $($files.Count) files from $SourceDir"

# ── build XML ─────────────────────────────────────────────────────────────────

$sb = [System.Text.StringBuilder]::new()

$null = $sb.AppendLine('<?xml version="1.0" encoding="UTF-8"?>')
$null = $sb.AppendLine('<!-- AUTO-GENERATED by harvest-agent.ps1 — DO NOT EDIT BY HAND -->')
$null = $sb.AppendLine('<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">')
$null = $sb.AppendLine('')
$null = $sb.AppendLine('  <Fragment>')

# Declare every subdirectory as a nested Directory element under INSTALLFOLDER
$dirs = $files |
    ForEach-Object { Split-Path $_.FullName -Parent } |
    Where-Object { $_ -ne $SourceDir } |
    Select-Object -Unique |
    Sort-Object

$dirMap = @{}   # abs path → WiX Directory Id

if ($dirs.Count -gt 0) {
    $null = $sb.AppendLine('    <DirectoryRef Id="INSTALLFOLDER">')

    foreach ($dir in $dirs) {
        $rel   = $dir.Substring($SourceDir.Length + 1)   # e.g. "runtimes\win-x64\native"
        $parts = $rel -split '\\'
        $depth = $parts.Count

        $indent = '      ' + ('  ' * ($depth - 1))
        $dirId  = 'dir_' + (To-WixId ($rel -replace '\\', '_'))
        $dirMap[$dir] = $dirId

        # We emit a flat list of DirectoryRef + Directory — simpler than nested
        # For multi-level paths we nest properly:
    }

    # Emit properly nested directories
    function Emit-Dir([string]$absPath, [string]$rel, [string]$indent) {
        $dirId = 'dir_' + (To-WixId ($rel -replace '\\', '_'))
        $dirMap[$absPath] = $dirId
        $name  = Split-Path $rel -Leaf
        $null = $sb.AppendLine("$indent<Directory Id=""$dirId"" Name=""$name"">")

        # children
        $childDirs = $dirs | Where-Object { (Split-Path $_ -Parent) -eq $absPath }
        foreach ($child in $childDirs) {
            $childRel = $child.Substring($SourceDir.Length + 1)
            Emit-Dir $child $childRel ($indent + '  ')
        }

        $null = $sb.AppendLine("$indent</Directory>")
    }

    # top-level dirs (parent == SourceDir)
    $topDirs = $dirs | Where-Object { (Split-Path $_ -Parent) -eq $SourceDir }
    foreach ($td in $topDirs) {
        $tdRel = $td.Substring($SourceDir.Length + 1)
        Emit-Dir $td $tdRel '      '
    }

    $null = $sb.AppendLine('    </DirectoryRef>')
    $null = $sb.AppendLine('')
}

# ── ComponentGroup ────────────────────────────────────────────────────────────

$null = $sb.AppendLine('    <ComponentGroup Id="AgentFiles" Directory="INSTALLFOLDER">')

$usedIds = @{}

foreach ($file in $files) {
    $relPath  = $file.FullName.Substring($SourceDir.Length + 1)   # e.g. appsettings.json
    $dirAbs   = Split-Path $file.FullName -Parent
    $isRoot   = ($dirAbs -eq $SourceDir)
    $isExe    = ($file.Name -eq 'KungConnect.Agent.exe')
    $isConfig = ($file.Name -eq 'appsettings.json') -and $isRoot

    # Unique WiX IDs
    $baseId  = To-WixId ($relPath -replace '\\', '_')
    $fileId  = "f_$baseId"
    $compId  = if ($isExe) { 'AgentExeComp' } elseif ($isConfig) { 'AppSettingsComp' } else { "c_$baseId" }

    # Guarantee uniqueness
    $suffix = 0
    $origComp = $compId
    while ($usedIds.ContainsKey($compId)) { $compId = "${origComp}_$suffix"; $suffix++ }
    $usedIds[$compId] = $true

    $guid    = New-DeterministicGuid $relPath
    $dirRef  = if ($isRoot) { '' } else { " Directory=""$($dirMap[$dirAbs])""" }
    $extraAttrs = if ($isConfig) { ' NeverOverwrite="yes" Permanent="yes"' } else { '' }

    $null = $sb.AppendLine('')
    $null = $sb.AppendLine("      <Component Id=\"$compId\" Guid=\"$guid\"$dirRef$extraAttrs>")

    if ($isExe) {
        $null = $sb.AppendLine("        <File Id=""$fileId"" Source=""`$(AgentBinDir)\$relPath"" KeyPath=""yes"" />")
        $null = $sb.AppendLine('')
        $null = $sb.AppendLine("        <!--")
        $null = $sb.AppendLine("          ServiceInstall is in the same component as the EXE (file key-path).")
        $null = $sb.AppendLine("          This ensures InstallServices is included in the MSI execute script.")
        $null = $sb.AppendLine("        -->")
        $null = $sb.AppendLine("        <ServiceInstall Id=""AgentServiceInstall""")
        $null = $sb.AppendLine("                        Name=""$ServiceName""")
        $null = $sb.AppendLine("                        DisplayName=""$ServiceDisplay""")
        $null = $sb.AppendLine("                        Description=""$ServiceDesc""")
        $null = $sb.AppendLine("                        Type=""ownProcess""")
        $null = $sb.AppendLine("                        Start=""auto""")
        $null = $sb.AppendLine("                        ErrorControl=""normal""")
        $null = $sb.AppendLine("                        Account=""LocalSystem"" />")
        $null = $sb.AppendLine("        <ServiceControl Id=""AgentServiceControl""")
        $null = $sb.AppendLine("                        Name=""$ServiceName""")
        $null = $sb.AppendLine("                        Stop=""both""")
        $null = $sb.AppendLine("                        Remove=""uninstall""")
        $null = $sb.AppendLine("                        Wait=\"yes\" />")  # wait for service to reach Stopped before CA_NotifyUninstall fires
    } elseif ($isConfig) {
        $null = $sb.AppendLine("        <File Id=""$fileId"" Source=""`$(AgentBinDir)\$relPath"" Vital=""no"" />")
    } else {
        $null = $sb.AppendLine("        <File Id=""$fileId"" Source=""`$(AgentBinDir)\$relPath"" />")
    }

    $null = $sb.AppendLine("      </Component>")
}

$null = $sb.AppendLine('')
$null = $sb.AppendLine('    </ComponentGroup>')
$null = $sb.AppendLine('  </Fragment>')
$null = $sb.AppendLine('')
$null = $sb.AppendLine('</Wix>')

# ── write output ──────────────────────────────────────────────────────────────

$outDir = Split-Path $OutputFile -Parent
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }

[System.IO.File]::WriteAllText($OutputFile, $sb.ToString(), [System.Text.Encoding]::UTF8)
Write-Host "Wrote: $OutputFile ($($files.Count) components)"
